/**
 * Mock Data for Credentialing Module
 *
 * This data integrates with the Provider Data Management system using real provider
 * information from mock-provider-data.ts. Each credentialing application is linked
 * to an actual provider record for realistic enterprise workflow simulation.
 *
 * Scenarios covered:
 * - Initial credentialing (new providers)
 * - Re-credentialing (3-year cycle renewals)
 * - Various workflow states (pending, in-progress, completed)
 * - Risk scenarios (sanctions matches, malpractice history)
 * - NCQA compliance tracking (120-day timeline)
 */

import type {
  CredentialingApplication,
  CredentialingDocument,
  PSVRequest,
  SanctionsScreening,
  CommitteeReview,
  RecredentialingCycle,
  CredentialingMetrics,
  ProviderSnapshot,
  AuditLogEntry,
} from "./credentialing-types"
import type { CommitteeMeeting } from "./credentialing-committee-types"

// ============================================================================
// Provider Snapshots - Captured from actual provider data at application time
// ============================================================================

const providerSnapshots: Record<number, ProviderSnapshot> = {
  198450: {
    provider_Id: 198450,
    npi: 1013941673,
    firstName: "David",
    lastName: "Weiner",
    middleName: "Martin",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "CD",
    currentCredStatus: "APPROVED",
    currentExpDate: "12/21/2026",
    initialApprovalDate: "10/10/2014",
  },
  198449: {
    provider_Id: 198449,
    npi: 1437143278,
    firstName: "Ojas",
    lastName: "Shah",
    middleName: "",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "CD",
    currentCredStatus: "APPROVED",
    currentExpDate: "03/15/2027",
    initialApprovalDate: "03/15/2018",
  },
  198448: {
    provider_Id: 198448,
    npi: 1225469216,
    firstName: "Nancy",
    lastName: "Serbellon",
    middleName: "",
    degree: "MD",
    specialty: "Internal Medicine",
    department: "Medicine",
    providerType: "Specialist",
    affiliationStatus: "CD",
    currentCredStatus: "APPROVED",
    currentExpDate: "06/30/2026",
    initialApprovalDate: "06/30/2017",
  },
  198447: {
    provider_Id: 198447,
    npi: 1982051652,
    firstName: "Michael",
    lastName: "Schulster",
    middleName: "Lawrence",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "CD",
    currentCredStatus: "APPROVED",
    currentExpDate: "09/30/2026",
    initialApprovalDate: "09/30/2020",
  },
  198444: {
    provider_Id: 198444,
    npi: 1891804746,
    firstName: "James",
    lastName: "McKiernan",
    middleName: "Michael",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "CD",
    currentCredStatus: "TERMINATED",
    currentExpDate: "12/20/2025",
    initialApprovalDate: "07/01/1996",
  },
  198442: {
    provider_Id: 198442,
    npi: 1891228565,
    firstName: "Ezra",
    lastName: "Margolin",
    middleName: "",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "APP",
    currentCredStatus: "PENDING",
    currentExpDate: "",
    initialApprovalDate: "",
  },
  198441: {
    provider_Id: 198441,
    npi: 1497198337,
    firstName: "Andrew",
    lastName: "Lenis",
    middleName: "Thomas",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "APP",
    currentCredStatus: "IN_PROGRESS",
    currentExpDate: "",
    initialApprovalDate: "",
  },
  198438: {
    provider_Id: 198438,
    npi: 1497512917,
    firstName: "Vivian",
    lastName: "Fu",
    middleName: "",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "CD",
    currentCredStatus: "APPROVED",
    currentExpDate: "04/30/2026",
    initialApprovalDate: "04/30/2023",
  },
  198434: {
    provider_Id: 198434,
    npi: 1881703890,
    firstName: "Kimberly",
    lastName: "Cooper",
    middleName: "Ann",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "CD",
    currentCredStatus: "CONDITIONAL",
    currentExpDate: "08/15/2026",
    initialApprovalDate: "08/15/2023",
  },
  198432: {
    provider_Id: 198432,
    npi: 1932363546,
    firstName: "Gina",
    lastName: "Badalato",
    middleName: "Marie",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "CD",
    currentCredStatus: "APPROVED",
    currentExpDate: "11/30/2026",
    initialApprovalDate: "11/30/2014",
  },
  198431: {
    provider_Id: 198431,
    npi: 1710152186,
    firstName: "Christopher",
    lastName: "Anderson",
    middleName: "James",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "CD",
    currentCredStatus: "APPROVED",
    currentExpDate: "02/28/2027",
    initialApprovalDate: "02/28/2021",
  },
  198429: {
    provider_Id: 198429,
    npi: 1003084203,
    firstName: "Joseph",
    lastName: "Alukal",
    middleName: "Philip",
    degree: "MD",
    specialty: "Urology",
    department: "Urology",
    providerType: "Specialist",
    affiliationStatus: "CD",
    currentCredStatus: "EXPIRED",
    currentExpDate: "01/15/2026",
    initialApprovalDate: "01/15/2020",
  },
}

// ============================================================================
// Credentialing Applications - Real Provider Integration
// ============================================================================

export const mockCredentialingApplications: CredentialingApplication[] = [
  // 1. APPROVED - Dr. David Weiner (Recently completed re-credentialing)
  {
    id: "CRED-2026-001",
    providerId: 198450,
    providerName: "Dr. David M. Weiner",
    providerNPI: 1013941673,
    providerSnapshot: providerSnapshots[198450],
    providerDegree: "MD",
    providerSpecialty: "Urology",
    providerDepartment: "Urology",
    affiliationStatus: "CD",
    cycleType: "recredentialing",
    status: "approved",
    currentStep: "Approved - Active Credential",
    applicationDate: "2025-09-15",
    targetCompletionDate: "2026-01-13",
    actualCompletionDate: "2025-12-18",
    expirationDate: "2028-12-18",
    nextRecredentialingDate: "2028-09-18",
    daysRemaining: 1062,
    progressPercentage: 100,
    assignedTo: "Jane Smith, Senior Credentialing Specialist",
    priority: "routine",
    slaDeadline: "2026-01-13",
    ncqaDeadline: "2026-01-13",
    riskScore: 0.3,
    riskLevel: "low",
    riskFactorSummary: [
      "Excellent credentialing history since 2014",
      "No malpractice claims",
      "All verifications completed within SLA",
    ],
    alerts: [],
    notes: [
      "Re-credentialing application received 2025-09-15",
      "All documents verified through Verisys partnership",
      "ABMS CertiFACTS confirmed board certification through 2032",
      "Committee approved unanimously - December 2025 meeting",
      "Provider notified of approval via secure portal",
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2025-09-15T09:00:00Z",
        action: "Application Submitted",
        performedBy: "Provider Portal",
        details: "Re-credentialing application auto-populated from prior cycle",
      },
      {
        id: "AUD-002",
        timestamp: "2025-12-18T14:30:00Z",
        action: "Application Approved",
        performedBy: "Dr. Robert Anderson, CMO",
        details: "Committee approval - unanimous vote",
      },
    ],
    createdAt: "2025-09-15T09:00:00Z",
    updatedAt: "2025-12-18T14:30:00Z",
  },

  // 2. PSV IN PROGRESS - Dr. Andrew Lenis (New provider, documents received)
  {
    id: "CRED-2026-002",
    providerId: 198441,
    providerName: "Dr. Andrew T. Lenis",
    providerNPI: 1497198337,
    providerSnapshot: providerSnapshots[198441],
    providerDegree: "MD",
    providerSpecialty: "Urology",
    providerDepartment: "Urology",
    affiliationStatus: "APP",
    cycleType: "initial",
    status: "psv_in_progress",
    currentStep: "Primary Source Verification - Awaiting State Board Response",
    applicationDate: "2026-01-05",
    targetCompletionDate: "2026-05-04",
    actualCompletionDate: null,
    expirationDate: null,
    nextRecredentialingDate: null,
    daysRemaining: 103,
    progressPercentage: 45,
    assignedTo: "Mike Chen, Credentialing Coordinator",
    priority: "expedited",
    slaDeadline: "2026-04-15",
    ncqaDeadline: "2026-05-05",
    riskScore: 1.2,
    riskLevel: "low",
    riskFactorSummary: [
      "New provider - initial credentialing",
      "Training verified at Columbia",
      "No adverse findings to date",
    ],
    alerts: [
      {
        id: "ALERT-001",
        type: "warning",
        category: "psv_delay",
        message: "NY State Medical Board verification pending for 12 days - Follow-up initiated",
        priority: "medium",
        createdAt: "2026-01-17T10:00:00Z",
        resolvedAt: null,
      },
      {
        id: "ALERT-002",
        type: "info",
        category: "expiration",
        message: "DEA registration expires 08/31/2026 - Within acceptable window",
        priority: "low",
        createdAt: "2026-01-21T08:00:00Z",
        resolvedAt: null,
      },
    ],
    notes: [
      "Initial credentialing for new urologist joining faculty",
      "Documents received via secure provider portal 2026-01-08",
      "AI extraction completed - High confidence (97.2%)",
      "PSV requests initiated 2026-01-10",
      "DEA verified via CSOS API - Active",
      "ABIM certification confirmed via CertiFACTS",
      "Awaiting NY State Medical Board response",
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2026-01-05T11:00:00Z",
        action: "Application Created",
        performedBy: "HR Integration",
        details: "New hire credentialing initiated",
      },
      {
        id: "AUD-002",
        timestamp: "2026-01-08T10:30:00Z",
        action: "Documents Uploaded",
        performedBy: "Dr. Andrew Lenis",
        details: "4 documents uploaded via provider portal",
      },
      {
        id: "AUD-003",
        timestamp: "2026-01-10T09:00:00Z",
        action: "PSV Initiated",
        performedBy: "Mike Chen",
        details: "Primary source verification requests sent to 5 entities",
      },
    ],
    createdAt: "2026-01-05T11:00:00Z",
    updatedAt: "2026-01-21T09:00:00Z",
  },

  // 3. COMMITTEE REVIEW - Dr. Kimberly Cooper (Malpractice history flagged)
  {
    id: "CRED-2026-003",
    providerId: 198434,
    providerName: "Dr. Kimberly A. Cooper",
    providerNPI: 1881703890,
    providerSnapshot: providerSnapshots[198434],
    providerDegree: "MD",
    providerSpecialty: "Urology",
    providerDepartment: "Urology",
    affiliationStatus: "CD",
    cycleType: "recredentialing",
    status: "committee_review",
    currentStep: "Credentialing Committee Review - Risk Assessment Required",
    applicationDate: "2025-11-20",
    targetCompletionDate: "2026-03-19",
    actualCompletionDate: null,
    expirationDate: "2026-08-15",
    nextRecredentialingDate: null,
    daysRemaining: 57,
    progressPercentage: 85,
    assignedTo: "Sarah Lee, Senior Credentialing Analyst",
    priority: "urgent",
    slaDeadline: "2026-02-28",
    ncqaDeadline: "2026-03-20",
    riskScore: 4.8,
    riskLevel: "medium",
    riskFactorSummary: [
      "NPDB: 2 malpractice settlements in past 5 years",
      "Settlement amounts: $350,000 (2024), $175,000 (2022)",
      "No pattern of gross negligence identified",
      "Peer review recommended",
    ],
    alerts: [
      {
        id: "ALERT-003",
        type: "warning",
        category: "sanction_match",
        message: "NPDB malpractice history: 2 settlements totaling $525,000 (2022-2024)",
        priority: "high",
        createdAt: "2025-12-01T10:00:00Z",
        resolvedAt: null,
      },
      {
        id: "ALERT-004",
        type: "info",
        category: "expiration",
        message: "Committee review scheduled for February 15, 2026 meeting",
        priority: "medium",
        createdAt: "2026-01-10T09:00:00Z",
        resolvedAt: null,
      },
    ],
    notes: [
      "Re-credentialing triggered by upcoming expiration 08/15/2026",
      "All PSV completed - No adverse licensure findings",
      "NPDB query returned 2 malpractice payment reports",
      "Both claims related to surgical complications - standard for specialty",
      "Escalated to committee for enhanced review per policy",
      "Dept Chair letter of support received",
      "Peer review file prepared for committee",
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2025-11-20T10:00:00Z",
        action: "Re-credentialing Initiated",
        performedBy: "System",
        details: "Auto-triggered 90 days before credential expiration",
      },
      {
        id: "AUD-002",
        timestamp: "2025-12-01T10:00:00Z",
        action: "Risk Flag Added",
        performedBy: "Sanctions Screening",
        details: "NPDB malpractice history flagged for review",
      },
      {
        id: "AUD-003",
        timestamp: "2026-01-10T09:00:00Z",
        action: "Committee Review Scheduled",
        performedBy: "Sarah Lee",
        details: "Scheduled for February 2026 committee meeting",
      },
    ],
    createdAt: "2025-11-20T10:00:00Z",
    updatedAt: "2026-01-21T11:00:00Z",
  },

  // 4. DENIED - Dr. James McKiernan (OIG Exclusion - Critical)
  {
    id: "CRED-2026-004",
    providerId: 198444,
    providerName: "Dr. James M. McKiernan",
    providerNPI: 1891804746,
    providerSnapshot: providerSnapshots[198444],
    providerDegree: "MD",
    providerSpecialty: "Urology",
    providerDepartment: "Urology",
    affiliationStatus: "TERMINATED",
    cycleType: "recredentialing",
    status: "denied",
    currentStep: "TERMINATED - OIG LEIE Exclusion",
    applicationDate: "2025-12-01",
    targetCompletionDate: "2026-03-31",
    actualCompletionDate: "2025-12-20",
    expirationDate: null,
    nextRecredentialingDate: null,
    daysRemaining: 0,
    progressPercentage: 100,
    assignedTo: "Compliance Team - URGENT",
    priority: "urgent",
    slaDeadline: "2025-12-20",
    ncqaDeadline: "2026-03-31",
    riskScore: 10.0,
    riskLevel: "high",
    riskFactorSummary: [
      "CRITICAL: OIG LEIE exclusion effective 2025-12-15",
      "Exclusion type: Criminal conviction - Healthcare fraud",
      "Federal programs participation prohibited",
      "Immediate termination required per CMS regulations",
    ],
    alerts: [
      {
        id: "ALERT-005",
        type: "error",
        category: "sanction_match",
        message: "CRITICAL: OIG LEIE Exclusion confirmed - Healthcare fraud conviction",
        priority: "urgent",
        createdAt: "2025-12-15T14:00:00Z",
        resolvedAt: "2025-12-20T16:00:00Z",
      },
    ],
    notes: [
      "OIG LEIE exclusion discovered during monthly screening 2025-12-15",
      "IMMEDIATE ACTION: All network privileges suspended same day",
      "Compliance notified CMS within 24 hours per requirement",
      "Termination letter sent via certified mail 2025-12-18",
      "Claims audit initiated for services since exclusion date",
      "Legal team engaged for potential False Claims Act exposure",
      "Provider appealing exclusion - Does not affect termination",
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2025-12-15T14:00:00Z",
        action: "CRITICAL: OIG Exclusion Detected",
        performedBy: "Automated Screening",
        details: "Monthly OIG LEIE scan identified exclusion",
      },
      {
        id: "AUD-002",
        timestamp: "2025-12-15T14:30:00Z",
        action: "Network Privileges Suspended",
        performedBy: "Compliance Team",
        details: "Immediate suspension per protocol",
      },
      {
        id: "AUD-003",
        timestamp: "2025-12-20T16:00:00Z",
        action: "Termination Executed",
        performedBy: "Dr. Robert Anderson, CMO",
        details: "Formal termination - OIG exclusion confirmed",
      },
    ],
    createdAt: "2025-12-01T09:00:00Z",
    updatedAt: "2025-12-20T16:00:00Z",
  },

  // 5. DOCUMENTS PENDING - Dr. Ezra Margolin (New provider, just started)
  {
    id: "CRED-2026-005",
    providerId: 198442,
    providerName: "Dr. Ezra Margolin",
    providerNPI: 1891228565,
    providerSnapshot: providerSnapshots[198442],
    providerDegree: "MD",
    providerSpecialty: "Urology",
    providerDepartment: "Urology",
    affiliationStatus: "APP",
    cycleType: "initial",
    status: "documents_pending",
    currentStep: "Awaiting Document Upload - Provider Notified",
    applicationDate: "2026-01-18",
    targetCompletionDate: "2026-05-17",
    actualCompletionDate: null,
    expirationDate: null,
    nextRecredentialingDate: null,
    daysRemaining: 116,
    progressPercentage: 10,
    assignedTo: "Tom Wilson, Credentialing Associate",
    priority: "routine",
    slaDeadline: "2026-05-01",
    ncqaDeadline: "2026-05-18",
    riskScore: 0.0,
    riskLevel: "low",
    riskFactorSummary: [
      "New provider - initial credentialing",
      "No risk factors identified yet",
      "Awaiting documentation for assessment",
    ],
    alerts: [
      {
        id: "ALERT-006",
        type: "info",
        category: "missing_document",
        message: "Provider portal access granted - Documents due by 02/01/2026",
        priority: "medium",
        createdAt: "2026-01-18T12:00:00Z",
        resolvedAt: null,
      },
    ],
    notes: [
      "Initial credentialing application created 2026-01-18",
      "Provider portal credentials sent via secure email",
      "Required documents list sent to provider",
      "HR confirmed start date: March 1, 2026",
      "Expedited processing may be needed based on start date",
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2026-01-18T12:00:00Z",
        action: "Application Created",
        performedBy: "HR Integration",
        details: "New hire credentialing initiated for March 2026 start",
      },
      {
        id: "AUD-002",
        timestamp: "2026-01-18T12:05:00Z",
        action: "Portal Access Granted",
        performedBy: "System",
        details: "Provider portal credentials generated and sent",
      },
    ],
    createdAt: "2026-01-18T12:00:00Z",
    updatedAt: "2026-01-21T08:00:00Z",
  },

  // 6. RECREDENTIALING DUE - Dr. Joseph Alukal (Expired, needs urgent attention)
  {
    id: "CRED-2026-006",
    providerId: 198429,
    providerName: "Dr. Joseph P. Alukal",
    providerNPI: 1003084203,
    providerSnapshot: providerSnapshots[198429],
    providerDegree: "MD",
    providerSpecialty: "Urology",
    providerDepartment: "Urology",
    affiliationStatus: "CD",
    cycleType: "recredentialing",
    status: "recredentialing_due",
    currentStep: "OVERDUE - Re-credentialing Required Immediately",
    applicationDate: "2023-01-15",
    targetCompletionDate: "2026-01-15",
    actualCompletionDate: null,
    expirationDate: "2026-01-15",
    nextRecredentialingDate: "2026-01-15",
    daysRemaining: -6,
    progressPercentage: 5,
    assignedTo: "Lisa Anderson, Re-credentialing Coordinator",
    priority: "urgent",
    slaDeadline: "2026-01-15",
    ncqaDeadline: "2026-01-15",
    riskScore: 2.5,
    riskLevel: "medium",
    riskFactorSummary: [
      "OVERDUE: Credential expired 01/15/2026",
      "Provider contacted 3 times - Limited response",
      "May require network suspension if not resolved",
      "Prior cycle: Approved without conditions",
    ],
    alerts: [
      {
        id: "ALERT-007",
        type: "error",
        category: "expiration",
        message: "CRITICAL: Credential EXPIRED on 01/15/2026 - Immediate action required",
        priority: "urgent",
        createdAt: "2026-01-16T08:00:00Z",
        resolvedAt: null,
      },
      {
        id: "ALERT-008",
        type: "warning",
        category: "psv_delay",
        message: "Provider non-responsive to re-credentialing outreach (3 attempts)",
        priority: "high",
        createdAt: "2026-01-10T09:00:00Z",
        resolvedAt: null,
      },
    ],
    notes: [
      "Prior credential approved: 01/15/2023 (3-year cycle)",
      "90-day notice sent: 10/15/2025 - No response",
      "60-day reminder sent: 11/15/2025 - No response",
      "30-day final notice sent: 12/15/2025 - No response",
      "Phone outreach 01/10/2026 - Voicemail left",
      "ESCALATED: Department Chair notified 01/16/2026",
      "Pending: May suspend privileges if no response by 01/25/2026",
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2025-10-15T09:00:00Z",
        action: "90-Day Notice Sent",
        performedBy: "System",
        details: "Re-credentialing notice sent via portal and email",
      },
      {
        id: "AUD-002",
        timestamp: "2025-11-15T09:00:00Z",
        action: "60-Day Reminder Sent",
        performedBy: "System",
        details: "Second notice - No response to initial notice",
      },
      {
        id: "AUD-003",
        timestamp: "2025-12-15T09:00:00Z",
        action: "Final Notice Sent",
        performedBy: "Lisa Anderson",
        details: "30-day final notice with suspension warning",
      },
      {
        id: "AUD-004",
        timestamp: "2026-01-16T08:00:00Z",
        action: "Credential Expired",
        performedBy: "System",
        details: "Credential expired - Escalated to management",
      },
    ],
    createdAt: "2023-01-15T10:00:00Z",
    updatedAt: "2026-01-21T09:00:00Z",
  },

  // 7. SANCTIONS SCREENING - Dr. Vivian Fu (In sanctions check phase)
  {
    id: "CRED-2026-007",
    providerId: 198438,
    providerName: "Dr. Vivian Fu",
    providerNPI: 1497512917,
    providerSnapshot: providerSnapshots[198438],
    providerDegree: "MD",
    providerSpecialty: "Urology",
    providerDepartment: "Urology",
    affiliationStatus: "CD",
    cycleType: "recredentialing",
    status: "sanctions_screening",
    currentStep: "Sanctions & Exclusions Screening - In Progress",
    applicationDate: "2025-12-10",
    targetCompletionDate: "2026-04-08",
    actualCompletionDate: null,
    expirationDate: "2026-04-30",
    nextRecredentialingDate: null,
    daysRemaining: 99,
    progressPercentage: 65,
    assignedTo: "Jennifer Martinez, Credentialing Analyst",
    priority: "routine",
    slaDeadline: "2026-04-01",
    ncqaDeadline: "2026-04-09",
    riskScore: 0.8,
    riskLevel: "low",
    riskFactorSummary: [
      "Re-credentialing on schedule",
      "PSV completed successfully",
      "Sanctions screening in progress - Standard timeline",
    ],
    alerts: [],
    notes: [
      "Re-credentialing application submitted 12/10/2025",
      "Documents verified - All current",
      "PSV completed 01/15/2026 - All sources verified",
      "Sanctions screening initiated 01/18/2026",
      "OIG/SAM/NPDB queries submitted - Awaiting results",
      "Expected completion: 01/25/2026",
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2025-12-10T10:00:00Z",
        action: "Application Submitted",
        performedBy: "Dr. Vivian Fu",
        details: "Re-credentialing application submitted via portal",
      },
      {
        id: "AUD-002",
        timestamp: "2026-01-18T09:00:00Z",
        action: "Sanctions Screening Initiated",
        performedBy: "Jennifer Martinez",
        details: "Queries submitted to OIG, SAM, NPDB, State databases",
      },
    ],
    createdAt: "2025-12-10T10:00:00Z",
    updatedAt: "2026-01-21T10:00:00Z",
  },

  // 8. CONDITIONAL APPROVAL - Dr. Gina Badalato (Approved with monitoring)
  {
    id: "CRED-2026-008",
    providerId: 198432,
    providerName: "Dr. Gina M. Badalato",
    providerNPI: 1932363546,
    providerSnapshot: providerSnapshots[198432],
    providerDegree: "MD",
    providerSpecialty: "Urology",
    providerDepartment: "Urology",
    affiliationStatus: "CD",
    cycleType: "recredentialing",
    status: "conditional_approval",
    currentStep: "Conditional Approval - Active with Monitoring",
    applicationDate: "2025-08-15",
    targetCompletionDate: "2025-12-13",
    actualCompletionDate: "2025-11-30",
    expirationDate: "2028-11-30",
    nextRecredentialingDate: "2028-08-30",
    daysRemaining: 1044,
    progressPercentage: 100,
    assignedTo: "Quality Assurance Team",
    priority: "routine",
    slaDeadline: "2025-12-13",
    ncqaDeadline: "2025-12-13",
    riskScore: 3.2,
    riskLevel: "medium",
    riskFactorSummary: [
      "Conditional approval due to DEA audit findings",
      "Required: Quarterly controlled substance audits",
      "Monitoring period: 12 months",
      "No adverse patient outcomes identified",
    ],
    alerts: [
      {
        id: "ALERT-009",
        type: "info",
        category: "expiration",
        message: "Quarterly audit due: 02/28/2026 - Reminder sent",
        priority: "medium",
        createdAt: "2026-01-15T09:00:00Z",
        resolvedAt: null,
      },
    ],
    notes: [
      "Re-credentialing approved with conditions 11/30/2025",
      "Condition: DEA audit identified documentation gaps",
      "Required: Quarterly controlled substance prescription audits",
      "First quarterly audit completed 12/31/2025 - Compliant",
      "Next audit due: 02/28/2026",
      "Full approval eligible after 12 months of compliance",
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2025-11-30T14:00:00Z",
        action: "Conditional Approval",
        performedBy: "Credentialing Committee",
        details: "Approved with quarterly monitoring conditions",
      },
      {
        id: "AUD-002",
        timestamp: "2025-12-31T16:00:00Z",
        action: "Q4 2025 Audit Completed",
        performedBy: "Pharmacy Compliance",
        details: "Controlled substance audit - Compliant",
      },
    ],
    createdAt: "2025-08-15T10:00:00Z",
    updatedAt: "2026-01-15T09:00:00Z",
  },

  // 9. EXTRACTION IN PROGRESS - Dr. Ojas Shah (Documents being processed)
  {
    id: "CRED-2026-009",
    providerId: 198449,
    providerName: "Dr. Ojas Shah",
    providerNPI: 1437143278,
    providerSnapshot: providerSnapshots[198449],
    providerDegree: "MD",
    providerSpecialty: "Urology",
    providerDepartment: "Urology",
    affiliationStatus: "CD",
    cycleType: "recredentialing",
    status: "extraction_in_progress",
    currentStep: "AI Data Extraction - Processing Documents",
    applicationDate: "2026-01-19",
    targetCompletionDate: "2026-05-18",
    actualCompletionDate: null,
    expirationDate: "2027-03-15",
    nextRecredentialingDate: null,
    daysRemaining: 418,
    progressPercentage: 25,
    assignedTo: "Mike Chen, Credentialing Coordinator",
    priority: "routine",
    slaDeadline: "2026-05-01",
    ncqaDeadline: "2026-05-19",
    riskScore: 0.5,
    riskLevel: "low",
    riskFactorSummary: [
      "Early re-credentialing submission (14 months before expiration)",
      "Excellent prior credentialing history",
      "No risk factors anticipated",
    ],
    alerts: [],
    notes: [
      "Proactive re-credentialing submission - 14 months early",
      "Documents uploaded 01/19/2026 via provider portal",
      "AI extraction initiated - Processing 6 documents",
      "Expected extraction completion: 01/22/2026",
      "Board certification expires 2030 - Ample validity",
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2026-01-19T14:00:00Z",
        action: "Documents Uploaded",
        performedBy: "Dr. Ojas Shah",
        details: "6 documents submitted via provider portal",
      },
      {
        id: "AUD-002",
        timestamp: "2026-01-19T14:05:00Z",
        action: "AI Extraction Started",
        performedBy: "System",
        details: "Verisys AI extraction initiated",
      },
    ],
    createdAt: "2026-01-19T14:00:00Z",
    updatedAt: "2026-01-21T08:00:00Z",
  },

  // 10. APPROVED - Dr. Christopher Anderson (Standard approval)
  {
    id: "CRED-2026-010",
    providerId: 198431,
    providerName: "Dr. Christopher J. Anderson",
    providerNPI: 1710152186,
    providerSnapshot: providerSnapshots[198431],
    providerDegree: "MD",
    providerSpecialty: "Urology",
    providerDepartment: "Urology",
    affiliationStatus: "CD",
    cycleType: "recredentialing",
    status: "approved",
    currentStep: "Approved - Active Credential",
    applicationDate: "2025-11-01",
    targetCompletionDate: "2026-02-28",
    actualCompletionDate: "2026-01-10",
    expirationDate: "2029-01-10",
    nextRecredentialingDate: "2028-10-10",
    daysRemaining: 1085,
    progressPercentage: 100,
    assignedTo: "Jane Smith, Senior Credentialing Specialist",
    priority: "routine",
    slaDeadline: "2026-02-28",
    ncqaDeadline: "2026-02-28",
    riskScore: 0.2,
    riskLevel: "low",
    riskFactorSummary: [
      "Clean credentialing history",
      "No sanctions or malpractice findings",
      "All verifications completed successfully",
    ],
    alerts: [],
    notes: [
      "Re-credentialing completed ahead of schedule",
      "All PSV verifications successful",
      "No sanctions findings",
      "Committee approved - January 2026 meeting",
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2025-11-01T10:00:00Z",
        action: "Application Submitted",
        performedBy: "Dr. Christopher Anderson",
        details: "Re-credentialing application submitted",
      },
      {
        id: "AUD-002",
        timestamp: "2026-01-10T14:00:00Z",
        action: "Application Approved",
        performedBy: "Credentialing Committee",
        details: "Approved - 3-year credential issued",
      },
    ],
    createdAt: "2025-11-01T10:00:00Z",
    updatedAt: "2026-01-10T14:00:00Z",
  },
]

// ============================================================================
// Documents - Linked to real provider applications
// ============================================================================

export const mockCredentialingDocuments: CredentialingDocument[] = [
  // Dr. Andrew Lenis (PSV in progress) - Documents
  {
    id: "DOC-001",
    applicationId: "CRED-2026-002",
    type: "state_license",
    name: "New York Medical License",
    fileName: "NY_License_MD287654.pdf",
    fileSize: 245000,
    uploadDate: "2026-01-08T10:30:00Z",
    status: "extracted",
    extractedData: {
      documentType: "state_license",
      extractionDate: "2026-01-08T10:35:00Z",
      confidence: 0.98,
      fields: {},
      alerts: [],
      license: {
        number: "287654",
        state: "New York",
        issueDate: "2020-07-01",
        expirationDate: "2028-07-01",
        status: "active",
        specialty: "Urology",
      },
    },
    verificationStatus: "not_verified",
    uploadedBy: "Dr. Andrew Lenis",
    notes: "Extracted successfully - PSV request sent to NY State Medical Board",
  },
  {
    id: "DOC-002",
    applicationId: "CRED-2026-002",
    type: "dea_registration",
    name: "DEA Certificate",
    fileName: "DEA_AL5678901.pdf",
    fileSize: 180000,
    uploadDate: "2026-01-08T10:32:00Z",
    status: "verified",
    extractedData: {
      documentType: "dea_registration",
      extractionDate: "2026-01-08T10:36:00Z",
      confidence: 0.95,
      fields: {},
      alerts: ["DEA expires in 7 months - Within acceptable window"],
      dea: {
        number: "AL5678901",
        issueDate: "2023-09-01",
        expirationDate: "2026-08-31",
        status: "active",
        schedules: ["II", "III", "IV", "V"],
      },
    },
    verificationStatus: "verified",
    uploadedBy: "Dr. Andrew Lenis",
    notes: "Verified via DEA CSOS API - Active registration confirmed",
  },
  {
    id: "DOC-003",
    applicationId: "CRED-2026-002",
    type: "board_certification",
    name: "American Board of Urology Certification",
    fileName: "ABU_Cert_Lenis_2022.pdf",
    fileSize: 320000,
    uploadDate: "2026-01-08T10:34:00Z",
    status: "verified",
    extractedData: {
      documentType: "board_certification",
      extractionDate: "2026-01-08T10:38:00Z",
      confidence: 0.99,
      fields: {},
      alerts: [],
      boardCertification: {
        board: "American Board of Urology",
        specialty: "Urology",
        certificationDate: "2022-03-15",
        expirationDate: "2032-03-15",
        status: "board_certified",
      },
    },
    verificationStatus: "verified",
    uploadedBy: "Dr. Andrew Lenis",
    notes: "Verified via ABMS CertiFACTS - Certification valid through 2032",
  },
  {
    id: "DOC-004",
    applicationId: "CRED-2026-002",
    type: "malpractice_insurance",
    name: "Malpractice Insurance Certificate",
    fileName: "Malpractice_MCIC_2025.pdf",
    fileSize: 290000,
    uploadDate: "2026-01-08T10:36:00Z",
    status: "extracted",
    extractedData: {
      documentType: "malpractice_insurance",
      extractionDate: "2026-01-08T10:40:00Z",
      confidence: 0.92,
      fields: {},
      alerts: [],
      malpracticeInsurance: {
        carrier: "MCIC Vermont Insurance, Inc.",
        policyNumber: "PR2026-AL001",
        coverageAmount: "$1,000,000 / $3,000,000",
        issueDate: "2025-01-01",
        expirationDate: "2026-12-31",
        coverageType: "claims_made",
      },
    },
    verificationStatus: "not_verified",
    uploadedBy: "Dr. Andrew Lenis",
    notes: "Coverage meets minimum requirements - Pending carrier verification",
  },

  // Dr. Ezra Margolin (Documents pending) - Placeholder
  {
    id: "DOC-005",
    applicationId: "CRED-2026-005",
    type: "state_license",
    name: "State Medical License - Pending",
    fileName: "",
    fileSize: 0,
    uploadDate: "",
    status: "pending_upload",
    extractedData: null,
    verificationStatus: "not_verified",
    uploadedBy: "",
    notes: "Awaiting document upload from provider - Due 02/01/2026",
  },

  // Dr. Ojas Shah (Extraction in progress) - Documents
  {
    id: "DOC-006",
    applicationId: "CRED-2026-009",
    type: "state_license",
    name: "New York Medical License",
    fileName: "NY_License_MD198765.pdf",
    fileSize: 235000,
    uploadDate: "2026-01-19T14:00:00Z",
    status: "uploaded",
    extractedData: null,
    verificationStatus: "not_verified",
    uploadedBy: "Dr. Ojas Shah",
    notes: "Uploaded - AI extraction in progress",
  },
  {
    id: "DOC-007",
    applicationId: "CRED-2026-009",
    type: "board_certification",
    name: "American Board of Urology Certification",
    fileName: "ABU_Cert_Shah_2020.pdf",
    fileSize: 310000,
    uploadDate: "2026-01-19T14:02:00Z",
    status: "uploaded",
    extractedData: null,
    verificationStatus: "not_verified",
    uploadedBy: "Dr. Ojas Shah",
    notes: "Uploaded - AI extraction in progress",
  },
]

// ============================================================================
// PSV Requests - Primary Source Verification
// ============================================================================

export const mockPSVRequests: PSVRequest[] = [
  // Dr. Andrew Lenis - PSV Requests
  {
    id: "PSV-001",
    applicationId: "CRED-2026-002",
    credentialType: "state_license",
    sourceType: "state_medical_board",
    sourceName: "New York State Education Department - Office of the Professions",
    contactEmail: "op4info@nysed.gov",
    status: "in_progress",
    requestDate: "2026-01-10T09:00:00Z",
    expectedResponseDate: "2026-01-24T17:00:00Z",
    actualResponseDate: null,
    verificationResult: null,
    followUpCount: 1,
    lastFollowUpDate: "2026-01-18T10:00:00Z",
    notes: [
      "Initial request sent 2026-01-10 via NY State online verification portal",
      "Follow-up email sent 2026-01-18 (no response after 8 days)",
      "Expected response by 2026-01-24 per SLA",
    ],
    priority: "high",
  },
  {
    id: "PSV-002",
    applicationId: "CRED-2026-002",
    credentialType: "dea_registration",
    sourceType: "dea",
    sourceName: "DEA Diversion Control Division - CSOS Online",
    contactEmail: "automated",
    status: "verified",
    requestDate: "2026-01-10T09:05:00Z",
    expectedResponseDate: "2026-01-10T09:10:00Z",
    actualResponseDate: "2026-01-10T09:06:00Z",
    verificationResult: {
      verified: true,
      verificationDate: "2026-01-10T09:06:00Z",
      verifiedBy: "DEA CSOS API",
      dataMatches: true,
      discrepancies: [],
      verifiedData: {
        deaNumber: "AL5678901",
        status: "active",
        expirationDate: "2026-08-31",
        schedules: ["II", "III", "IV", "V"],
        registrantName: "Andrew T. Lenis, MD",
      },
      confidenceLevel: 1.0,
      documentation: ["DEA CSOS API Response - 2026-01-10 09:06:00"],
    },
    followUpCount: 0,
    lastFollowUpDate: null,
    notes: [
      "Automated API verification - Real-time response",
      "Status: Active registration confirmed",
      "All data matches submitted documentation",
    ],
    priority: "normal",
  },
  {
    id: "PSV-003",
    applicationId: "CRED-2026-002",
    credentialType: "board_certification",
    sourceType: "abms_certifacts",
    sourceName: "ABMS CertiFACTS - American Board of Urology",
    contactEmail: "automated",
    status: "verified",
    requestDate: "2026-01-10T09:10:00Z",
    expectedResponseDate: "2026-01-11T09:00:00Z",
    actualResponseDate: "2026-01-10T14:30:00Z",
    verificationResult: {
      verified: true,
      verificationDate: "2026-01-10T14:30:00Z",
      verifiedBy: "ABMS CertiFACTS Database",
      dataMatches: true,
      discrepancies: [],
      verifiedData: {
        board: "American Board of Urology",
        specialty: "Urology",
        certificationDate: "2022-03-15",
        expirationDate: "2032-03-15",
        status: "Certified",
        mocStatus: "Meeting MOC Requirements",
      },
      confidenceLevel: 1.0,
      documentation: ["ABMS CertiFACTS Query Result - 2026-01-10"],
    },
    followUpCount: 0,
    lastFollowUpDate: null,
    notes: [
      "Database lookup completed within hours",
      "Board certification confirmed through 2032",
      "MOC (Maintenance of Certification) status: Current",
    ],
    priority: "normal",
  },

  // Dr. Kimberly Cooper - PSV Requests (Committee Review)
  {
    id: "PSV-004",
    applicationId: "CRED-2026-003",
    credentialType: "state_license",
    sourceType: "state_medical_board",
    sourceName: "New York State Education Department - Office of the Professions",
    contactEmail: "op4info@nysed.gov",
    status: "verified",
    requestDate: "2025-12-05T10:00:00Z",
    expectedResponseDate: "2025-12-19T17:00:00Z",
    actualResponseDate: "2025-12-15T11:30:00Z",
    verificationResult: {
      verified: true,
      verificationDate: "2025-12-15T11:30:00Z",
      verifiedBy: "NY State Education Department Verification Unit",
      dataMatches: true,
      discrepancies: [],
      verifiedData: {
        licenseNumber: "245678",
        status: "Active - Current Registration",
        issueDate: "2015-07-01",
        expirationDate: "2027-07-01",
        disciplinaryActions: "None on record",
      },
      confidenceLevel: 1.0,
      documentation: ["NY State Official Verification Letter - 2025-12-15"],
    },
    followUpCount: 0,
    lastFollowUpDate: null,
    notes: [
      "Verification completed within SLA",
      "No disciplinary history on record",
      "License in good standing",
    ],
    priority: "normal",
  },
]

// ============================================================================
// Sanctions Screenings - OIG, SAM, NPDB, State databases
// ============================================================================

export const mockSanctionsScreenings: SanctionsScreening[] = [
  // Dr. Andrew Lenis - Clean screening
  {
    id: "SANC-001",
    applicationId: "CRED-2026-002",
    providerId: 198441,
    screeningDate: "2026-01-10T08:00:00Z",
    databases: ["oig_leie", "sam_gov", "npdb", "state_medicaid", "state_medical_board"],
    matchesFound: [],
    status: "clear",
    screenedBy: "Automated Monthly Screening",
    notes: [
      "All databases queried - No matches found",
      "OIG LEIE: Clear",
      "SAM.gov: Clear",
      "NPDB: No reports",
      "NY State Medicaid: Clear",
      "Provider cleared for network participation pending license verification",
    ],
  },

  // Dr. Kimberly Cooper - NPDB malpractice history
  {
    id: "SANC-002",
    applicationId: "CRED-2026-003",
    providerId: 198434,
    screeningDate: "2025-12-01T08:00:00Z",
    databases: ["oig_leie", "sam_gov", "npdb", "state_medicaid", "state_medical_board"],
    matchesFound: [
      {
        id: "MATCH-001",
        database: "npdb",
        matchType: "npi",
        confidence: "high",
        matchedEntity: {
          name: "Kimberly Ann Cooper, MD",
          npi: "1881703890",
          exclusionType: "Medical Malpractice Payment Report",
          exclusionDate: "2024-06-15",
          reason: "Malpractice settlement - Surgical complication - $350,000",
        },
        isFalsePositive: false,
        investigationStatus: "confirmed",
        resolution: "Flagged for committee review - Settlement within specialty norms",
        resolvedDate: "2025-12-05T10:00:00Z",
        resolvedBy: "Sarah Lee, Senior Credentialing Analyst",
      },
      {
        id: "MATCH-002",
        database: "npdb",
        matchType: "npi",
        confidence: "high",
        matchedEntity: {
          name: "Kimberly Ann Cooper, MD",
          npi: "1881703890",
          exclusionType: "Medical Malpractice Payment Report",
          exclusionDate: "2022-09-20",
          reason: "Malpractice settlement - Post-operative infection - $175,000",
        },
        isFalsePositive: false,
        investigationStatus: "confirmed",
        resolution: "Flagged for committee review - Prior settlement",
        resolvedDate: "2025-12-05T10:00:00Z",
        resolvedBy: "Sarah Lee, Senior Credentialing Analyst",
      },
    ],
    status: "under_review",
    screenedBy: "Automated Monthly Screening",
    notes: [
      "NPDB: 2 malpractice payment reports identified",
      "Total settlements: $525,000 over 3 years",
      "OIG LEIE: Clear - No exclusions",
      "SAM.gov: Clear - No debarment",
      "Both claims related to surgical complications - Common in urology",
      "Escalated to committee for risk assessment",
      "Department Chair attestation received",
    ],
  },

  // Dr. James McKiernan - OIG LEIE Exclusion (CRITICAL)
  {
    id: "SANC-003",
    applicationId: "CRED-2026-004",
    providerId: 198444,
    screeningDate: "2025-12-15T08:00:00Z",
    databases: ["oig_leie", "sam_gov", "npdb", "state_medicaid", "state_medical_board"],
    matchesFound: [
      {
        id: "MATCH-003",
        database: "oig_leie",
        matchType: "npi",
        confidence: "high",
        matchedEntity: {
          name: "James Michael McKiernan, MD",
          npi: "1891804746",
          exclusionType: "1128(a)(1) - Conviction of program-related crimes",
          exclusionDate: "2025-12-15",
          reason: "Criminal conviction - Healthcare fraud involving federal healthcare programs",
        },
        isFalsePositive: false,
        investigationStatus: "confirmed",
        resolution: "IMMEDIATE TERMINATION - Federal exclusion confirmed",
        resolvedDate: "2025-12-20T16:00:00Z",
        resolvedBy: "Compliance Team",
      },
    ],
    status: "resolved",
    screenedBy: "Automated Monthly Screening",
    notes: [
      "CRITICAL: OIG LEIE exclusion discovered",
      "Exclusion Type: 1128(a)(1) - Mandatory exclusion",
      "Effective Date: December 15, 2025",
      "IMMEDIATE ACTION: Network privileges suspended same day",
      "Compliance notification sent to CMS",
      "Claims audit initiated for post-exclusion services",
      "Termination letter sent via certified mail",
      "Legal team engaged for potential FCA exposure",
    ],
  },

  // Dr. Vivian Fu - Screening in progress
  {
    id: "SANC-004",
    applicationId: "CRED-2026-007",
    providerId: 198438,
    screeningDate: "2026-01-18T08:00:00Z",
    databases: ["oig_leie", "sam_gov", "npdb", "state_medicaid", "state_medical_board"],
    matchesFound: [],
    status: "clear",
    screenedBy: "Automated Screening - Re-credentialing",
    notes: [
      "Screening initiated 2026-01-18",
      "OIG LEIE: Clear",
      "SAM.gov: Clear",
      "NPDB: Query submitted - Results pending",
      "NY State databases: Clear",
      "Expected completion: 2026-01-25",
    ],
  },
]

// ============================================================================
// Committee Reviews - Decision documentation
// ============================================================================

export const mockCommitteeReviews: CommitteeReview[] = [
  // Dr. David Weiner - Standard Approval
  {
    id: "COMM-001",
    applicationId: "CRED-2026-001",
    committeeId: "CRED-COMM-2025-12",
    committeeName: "Credentialing Committee - December 2025",
    meetingDate: "2025-12-15T14:00:00Z",
    reviewDate: "2025-12-15T14:00:00Z",
    decision: "approve",
    riskScore: 0.3,
    riskLevel: "low",
    riskFactors: [
      {
        category: "Licensing Status",
        description: "Active NY license in good standing - No disciplinary actions since 2014",
        score: 0,
        weight: 0.2,
        weightedScore: 0.0,
        severity: "low",
      },
      {
        category: "Board Certification",
        description: "American Board of Urology - Certified through 2032, MOC current",
        score: 0,
        weight: 0.2,
        weightedScore: 0.0,
        severity: "low",
      },
      {
        category: "Sanctions/Exclusions",
        description: "No sanctions or exclusions found across all databases",
        score: 0,
        weight: 0.2,
        weightedScore: 0.0,
        severity: "low",
      },
      {
        category: "Malpractice History",
        description: "No malpractice claims in 10+ year history",
        score: 0,
        weight: 0.2,
        weightedScore: 0.0,
        severity: "low",
      },
      {
        category: "Employment Stability",
        description: "Continuous employment at Columbia since 2014 (10+ years)",
        score: 0,
        weight: 0.1,
        weightedScore: 0.0,
        severity: "low",
      },
      {
        category: "Credential Renewal",
        description: "All credentials current with appropriate validity periods",
        score: 0,
        weight: 0.1,
        weightedScore: 0.0,
        severity: "low",
      },
    ],
    recommendation: "APPROVE - Exemplary credentialing profile with no concerns",
    conditions: [],
    votingMembers: [
      { id: "MEM-001", name: "Dr. Robert Anderson", title: "Chief Medical Officer", role: "Chair", vote: "approve" },
      { id: "MEM-002", name: "Dr. Lisa Wong", title: "Medical Director", role: "Member", vote: "approve" },
      { id: "MEM-003", name: "Sarah Mitchell", title: "VP Quality & Safety", role: "Member", vote: "approve" },
      { id: "MEM-004", name: "Dr. Michael Chen", title: "Department Chair, Urology", role: "Member", vote: "approve" },
    ],
    voteSummary: { approve: 4, deny: 0, defer: 0, abstain: 0 },
    executiveSummary: `**APPLICANT**: Dr. David M. Weiner, MD - Urology
**APPLICATION TYPE**: Re-credentialing (3-year cycle)
**RECOMMENDATION**: APPROVE

**PSV RESULTS**: All required credentials verified through primary sources:
- Medical License (NY): Verified ✓ - Active through 2028
- DEA Registration: Verified ✓ - Active
- Board Certification (ABU): Verified ✓ - Through 2032
- Hospital Privileges: Verified ✓ - NYP/Columbia
- Malpractice Insurance: Verified ✓ - MCIC $5M/$5M

**SANCTIONS SCREENING**: Clear across all databases (OIG, SAM, NPDB, State)

**RISK ASSESSMENT**: LOW (0.3/10) - Exemplary profile

**MOTION**: Approve for network participation for 3-year cycle effective immediately`,
    detailedNotes: "Exemplary application with 10+ years of clean credentialing history. All committee members voted unanimously to approve. Provider continues as valued network participant.",
    approvedBy: "Dr. Robert Anderson, Chief Medical Officer",
    approvalDate: "2025-12-15T14:30:00Z",
  },

  // Dr. Kimberly Cooper - Conditional Approval (Scheduled for February)
  {
    id: "COMM-002",
    applicationId: "CRED-2026-003",
    committeeId: "CRED-COMM-2026-02",
    committeeName: "Credentialing Committee - February 2026",
    meetingDate: "2026-02-15T14:00:00Z",
    reviewDate: "2026-02-15T14:00:00Z",
    decision: "conditional_approval",
    riskScore: 4.8,
    riskLevel: "medium",
    riskFactors: [
      {
        category: "Licensing Status",
        description: "Active NY license - No disciplinary actions",
        score: 0,
        weight: 0.2,
        weightedScore: 0.0,
        severity: "low",
      },
      {
        category: "Board Certification",
        description: "American Board of Urology - Certified, current",
        score: 0,
        weight: 0.2,
        weightedScore: 0.0,
        severity: "low",
      },
      {
        category: "Sanctions/Exclusions",
        description: "No OIG/SAM exclusions",
        score: 0,
        weight: 0.2,
        weightedScore: 0.0,
        severity: "low",
      },
      {
        category: "Malpractice History",
        description: "NPDB: 2 settlements totaling $525,000 (2022, 2024)",
        score: 8,
        weight: 0.2,
        weightedScore: 1.6,
        severity: "high",
      },
      {
        category: "Employment Stability",
        description: "Stable - 8 years at current institution",
        score: 0,
        weight: 0.1,
        weightedScore: 0.0,
        severity: "low",
      },
      {
        category: "Credential Renewal",
        description: "All credentials current",
        score: 0,
        weight: 0.1,
        weightedScore: 0.0,
        severity: "low",
      },
    ],
    recommendation: "CONDITIONAL APPROVAL - Enhanced monitoring due to malpractice history",
    conditions: [
      "Focused peer review of surgical cases within 90 days",
      "Quarterly malpractice claims reporting for 12 months",
      "Maintain minimum $1M/$3M malpractice coverage",
      "Immediate reporting of any new claims or suits within 10 business days",
    ],
    votingMembers: [
      { id: "MEM-001", name: "Dr. Robert Anderson", title: "Chief Medical Officer", role: "Chair", vote: "approve" },
      { id: "MEM-002", name: "Dr. Lisa Wong", title: "Medical Director", role: "Member", vote: "approve" },
      { id: "MEM-003", name: "Sarah Mitchell", title: "VP Quality & Safety", role: "Member", vote: "defer" },
      { id: "MEM-004", name: "Dr. Michael Chen", title: "Department Chair, Urology", role: "Member", vote: "approve" },
    ],
    voteSummary: { approve: 3, deny: 0, defer: 1, abstain: 0 },
    executiveSummary: `**APPLICANT**: Dr. Kimberly A. Cooper, MD - Urology
**APPLICATION TYPE**: Re-credentialing
**RECOMMENDATION**: CONDITIONAL APPROVAL

**PSV RESULTS**: All credentials verified ✓

**SANCTIONS SCREENING**:
- OIG/SAM: Clear
- NPDB: 2 Malpractice Payment Reports
  • 2024: $350,000 - Surgical complication
  • 2022: $175,000 - Post-operative infection

**RISK ASSESSMENT**: MEDIUM (4.8/10) - Elevated malpractice history

**COMMITTEE DISCUSSION**:
Both claims relate to surgical complications - inherently high-risk specialty. Department Chair provided attestation of competence. No pattern of gross negligence. Settlements within norms for urologic surgery.

**CONDITIONS**:
1. Focused peer review within 90 days
2. Quarterly claims monitoring (12 months)
3. Immediate new claim reporting

**MOTION**: Conditional approval with enhanced monitoring`,
    detailedNotes: "Committee discussed malpractice history at length. VP Quality requested deferral pending additional peer review, but majority voted for conditional approval with monitoring. Department Chair attestation was persuasive - both cases involved complex reconstructive procedures.",
    approvedBy: "Dr. Robert Anderson, Chief Medical Officer",
    approvalDate: "2026-02-15T15:00:00Z",
  },
]

// ============================================================================
// Committee Meetings - Meeting scheduling and management
// ============================================================================

export const mockCommitteeMeetings: CommitteeMeeting[] = [
  {
    id: "meeting-001",
    name: "January 2025 Credentialing Committee Review",
    scheduledDate: "2025-01-25T09:00:00",
    location: "Conference Room A, Medical Staff Office",
    status: "scheduled",
    chairId: "cm-001",
    chairName: "Dr. Michael Chen",
    attendees: [
      {
        userId: "cm-001",
        name: "Dr. Michael Chen",
        title: "Chief Medical Officer",
        role: "chair",
        attendanceStatus: "confirmed",
        votingEligible: true,
      },
      {
        userId: "cm-002",
        name: "Dr. Sarah Martinez",
        title: "Director of Quality & Safety",
        role: "member",
        attendanceStatus: "confirmed",
        votingEligible: true,
      },
      {
        userId: "cm-003",
        name: "Dr. James Thompson",
        title: "Department Chief - Medicine",
        role: "member",
        attendanceStatus: "pending",
        votingEligible: true,
      },
      {
        userId: "cm-004",
        name: "Nancy Williams, RN",
        title: "VP of Clinical Operations",
        role: "member",
        attendanceStatus: "confirmed",
        votingEligible: true,
      },
      {
        userId: "cm-005",
        name: "Robert Johnson, JD",
        title: "Chief Compliance Officer",
        role: "member",
        attendanceStatus: "confirmed",
        votingEligible: true,
      },
      {
        userId: "cm-006",
        name: "Dr. Emily Davis",
        title: "Medical Staff President",
        role: "member",
        attendanceStatus: "confirmed",
        votingEligible: true,
      },
    ],
    agenda: [
      {
        id: "agenda-001",
        order: 1,
        type: "application_review",
        title: "Review of Dr. David Weiner - Initial Application",
        description: "Urology specialist seeking initial credentials",
        applicationId: "CRED-2026-001",
        estimatedMinutes: 15,
        status: "pending",
      },
      {
        id: "agenda-002",
        order: 2,
        type: "application_review",
        title: "Review of Dr. Vivian Fu - Re-credentialing",
        description: "2-year re-credentialing cycle - Gastroenterology",
        applicationId: "CRED-2026-007",
        estimatedMinutes: 10,
        status: "pending",
      },
      {
        id: "agenda-003",
        order: 3,
        type: "policy_discussion",
        title: "Updates to NCQA Credentialing Standards",
        description: "Review new 2025 requirements and implementation plan",
        estimatedMinutes: 20,
        status: "pending",
      },
    ],
    applications: ["CRED-2026-001", "CRED-2026-007"],
    createdBy: "user-001",
    createdAt: "2025-01-15T10:00:00",
  },
  {
    id: "meeting-002",
    name: "December 2024 Committee Meeting",
    scheduledDate: "2024-12-20T14:00:00",
    location: "Virtual - Zoom",
    status: "completed",
    chairId: "cm-001",
    chairName: "Dr. Michael Chen",
    attendees: [
      {
        userId: "cm-001",
        name: "Dr. Michael Chen",
        title: "Chief Medical Officer",
        role: "chair",
        attendanceStatus: "attended",
        votingEligible: true,
      },
      {
        userId: "cm-002",
        name: "Dr. Sarah Martinez",
        title: "Director of Quality & Safety",
        role: "member",
        attendanceStatus: "attended",
        votingEligible: true,
      },
      {
        userId: "cm-004",
        name: "Nancy Williams, RN",
        title: "VP of Clinical Operations",
        role: "member",
        attendanceStatus: "absent",
        votingEligible: true,
      },
    ],
    agenda: [],
    applications: [],
    createdBy: "user-001",
    createdAt: "2024-12-10T09:00:00",
  },
  {
    id: "meeting-003",
    name: "February 2025 Emergency Meeting",
    scheduledDate: "2025-02-01T16:00:00",
    location: "Hybrid - Conference Room B + Zoom",
    status: "scheduled",
    chairId: "cm-001",
    chairName: "Dr. Michael Chen",
    attendees: [
      {
        userId: "cm-001",
        name: "Dr. Michael Chen",
        title: "Chief Medical Officer",
        role: "chair",
        attendanceStatus: "confirmed",
        votingEligible: true,
      },
      {
        userId: "cm-005",
        name: "Robert Johnson, JD",
        title: "Chief Compliance Officer",
        role: "member",
        attendanceStatus: "confirmed",
        votingEligible: true,
      },
    ],
    agenda: [
      {
        id: "agenda-004",
        order: 1,
        type: "application_review",
        title: "Urgent Review - Sanctions Match Resolution",
        description: "Review false positive determination for OIG-LEIE match",
        applicationId: "CRED-2026-003",
        estimatedMinutes: 30,
        status: "pending",
      },
    ],
    applications: ["CRED-2026-003"],
    createdBy: "user-001",
    createdAt: "2025-01-28T08:00:00",
  },
]

// ============================================================================
// Re-credentialing Cycles - Tracking 3-year cycles
// ============================================================================

export const mockRecredentialingCycles: RecredentialingCycle[] = [
  // Dr. Joseph Alukal - OVERDUE
  {
    id: "RECRED-001",
    providerId: 198429,
    priorApplicationId: "CRED-2023-100",
    currentApplicationId: "CRED-2026-006",
    cycleNumber: 2,
    priorApprovalDate: "2023-01-15",
    expirationDate: "2026-01-15",
    noticeDate: "2025-10-15",
    submissionDeadline: "2025-12-15",
    status: "overdue",
    daysSinceNotice: 98,
    daysUntilExpiration: -6,
    isOverdue: true,
    fastTrackEligible: false,
    changesReported: false,
    materialChanges: [],
    outreachHistory: [
      {
        id: "OUT-001",
        date: "2025-10-15",
        method: "email",
        contactedBy: "System - Automated",
        response: null,
        responseDate: null,
      },
      {
        id: "OUT-002",
        date: "2025-10-15",
        method: "portal_notification",
        contactedBy: "System - Automated",
        response: null,
        responseDate: null,
      },
      {
        id: "OUT-003",
        date: "2025-11-15",
        method: "email",
        contactedBy: "Lisa Anderson",
        response: null,
        responseDate: null,
      },
      {
        id: "OUT-004",
        date: "2025-12-15",
        method: "mail",
        contactedBy: "Lisa Anderson",
        response: null,
        responseDate: null,
      },
      {
        id: "OUT-005",
        date: "2026-01-10",
        method: "phone",
        contactedBy: "Lisa Anderson",
        response: "Voicemail left - Provider did not answer",
        responseDate: null,
      },
    ],
  },

  // Dr. Vivian Fu - Active re-credentialing in progress
  {
    id: "RECRED-002",
    providerId: 198438,
    priorApplicationId: "CRED-2023-050",
    currentApplicationId: "CRED-2026-007",
    cycleNumber: 1,
    priorApprovalDate: "2023-04-30",
    expirationDate: "2026-04-30",
    noticeDate: "2025-12-01",
    submissionDeadline: "2026-03-01",
    status: "submitted",
    daysSinceNotice: 51,
    daysUntilExpiration: 99,
    isOverdue: false,
    fastTrackEligible: true,
    changesReported: false,
    materialChanges: [],
    outreachHistory: [
      {
        id: "OUT-001",
        date: "2025-12-01",
        method: "email",
        contactedBy: "System - Automated",
        response: "Application submitted",
        responseDate: "2025-12-10",
      },
      {
        id: "OUT-002",
        date: "2025-12-01",
        method: "portal_notification",
        contactedBy: "System - Automated",
        response: "Acknowledged via portal",
        responseDate: "2025-12-05",
      },
    ],
  },
]

// ============================================================================
// Dashboard Metrics - Real-time calculations
// ============================================================================

export const mockCredentialingMetrics: CredentialingMetrics = {
  totalApplications: 10,
  byStatus: {
    not_started: 0,
    documents_pending: 1,
    documents_received: 0,
    extraction_in_progress: 1,
    psv_in_progress: 1,
    sanctions_screening: 1,
    committee_review: 1,
    approved: 2,
    denied: 1,
    conditional_approval: 1,
    deferred: 0,
    expired: 0,
    recredentialing_due: 1,
  },
  avgTimeToApproval: 58,
  approvalRate: 85.7,
  psvCompletionRate: 94.2,
  sanctionsMatches: 3,
  overdueRecredentialing: 1,
  upcomingExpirations: 2,
  committeeBacklog: 1,
}

// ============================================================================
// Credentialing Staff / Assignees
// ============================================================================

export const credentialingStaff = [
  { id: "STAFF-001", name: "Jane Smith", title: "Senior Credentialing Specialist", email: "jsmith@org.com" },
  { id: "STAFF-002", name: "Mike Chen", title: "Credentialing Coordinator", email: "mchen@org.com" },
  { id: "STAFF-003", name: "Sarah Lee", title: "Senior Credentialing Analyst", email: "slee@org.com" },
  { id: "STAFF-004", name: "Tom Wilson", title: "Credentialing Associate", email: "twilson@org.com" },
  { id: "STAFF-005", name: "Lisa Anderson", title: "Re-credentialing Coordinator", email: "landerson@org.com" },
  { id: "STAFF-006", name: "Jennifer Martinez", title: "Credentialing Analyst", email: "jmartinez@org.com" },
]

// ============================================================================
// Filter Options for UI
// ============================================================================

export const credentialingFilterOptions = {
  statuses: [
    { id: "not_started", label: "Not Started" },
    { id: "documents_pending", label: "Documents Pending" },
    { id: "documents_received", label: "Documents Received" },
    { id: "extraction_in_progress", label: "Extracting Data" },
    { id: "psv_in_progress", label: "PSV In Progress" },
    { id: "sanctions_screening", label: "Sanctions Screening" },
    { id: "committee_review", label: "Committee Review" },
    { id: "approved", label: "Approved" },
    { id: "denied", label: "Denied" },
    { id: "conditional_approval", label: "Conditional Approval" },
    { id: "deferred", label: "Deferred" },
    { id: "expired", label: "Expired" },
    { id: "recredentialing_due", label: "Re-Cred Due" },
  ],
  cycleTypes: [
    { id: "initial", label: "Initial Credentialing" },
    { id: "recredentialing", label: "Re-credentialing" },
  ],
  riskLevels: [
    { id: "low", label: "Low Risk" },
    { id: "medium", label: "Medium Risk" },
    { id: "high", label: "High Risk" },
  ],
  priorities: [
    { id: "routine", label: "Routine" },
    { id: "expedited", label: "Expedited" },
    { id: "urgent", label: "Urgent" },
  ],
  departments: [
    { id: "urology", label: "Urology" },
    { id: "medicine", label: "Medicine" },
    { id: "surgery", label: "Surgery" },
    { id: "pediatrics", label: "Pediatrics" },
    { id: "obgyn", label: "OB/GYN" },
  ],
}
