import type { PayerExchangeResponse, CycleHistoryResponse } from "./payer-exchange-types"

export const mockPayerExchangeData: PayerExchangeResponse = {
  account_id: 0,
  health_plan_id: 0,
  cycle_id: 0,
  cycle_round_id: 0,
  is_successful: true,
  errors: [],
  response_data: [
    {
      health_plan_id: 339,
      health_plan_name: "Aetna",
      health_plan_code: "43",
      health_plan_status: "File Generation triggered",
      health_plan_status_date: "01/16/2026 09:00 AM",
      health_plan_cycle_name: "16_January_26_21_00",
      health_plan_cycle_start_date: "01/16/2026",
      time_elapsed: null,
      cycle_errors_and_fixes_summary: "",
      is_cycle_reschedule_allowed: false,
      round_id: 0,
      health_plan_round_name: "",
      health_plan_icon_color: "Gray",
      health_plan_image_url: "",
      upload_id: 0,
      cycle_id: 76338,
      total_provider: 2813,
      file_type: 0,
      total_discrepancies: 0,
      fixed: 0,
      excel_url: null,
      totalAddition: 0,
      totalChanges: 0,
      totalTermination: 0,
    },
    {
      health_plan_id: 340,
      health_plan_name: "Aetna Mcare",
      health_plan_code: "396",
      health_plan_status: "File Generation triggered",
      health_plan_status_date: "01/17/2026 01:55 AM",
      health_plan_cycle_name: "17_January_26_01_55",
      health_plan_cycle_start_date: "01/17/2026",
      time_elapsed: null,
      cycle_errors_and_fixes_summary: "",
      is_cycle_reschedule_allowed: false,
      round_id: 0,
      health_plan_round_name: "",
      health_plan_icon_color: "Gray",
      health_plan_image_url: "",
      upload_id: 0,
      cycle_id: 76397,
      total_provider: 0,
      file_type: 0,
      total_discrepancies: 0,
      fixed: 0,
      excel_url: null,
      totalAddition: 0,
      totalChanges: 0,
      totalTermination: 0,
    },
    {
      health_plan_id: 341,
      health_plan_name: "Affinity",
      health_plan_code: "101",
      health_plan_status: "Cycle Not Configured",
      health_plan_status_date: "",
      health_plan_cycle_name: "",
      health_plan_cycle_start_date: "",
      time_elapsed: null,
      cycle_errors_and_fixes_summary: "",
      is_cycle_reschedule_allowed: false,
      round_id: 0,
      health_plan_round_name: "",
      health_plan_icon_color: "Red",
      health_plan_image_url: "",
      upload_id: 0,
      cycle_id: 0,
      total_provider: 0,
      file_type: 0,
      total_discrepancies: 0,
      fixed: 0,
      excel_url: null,
      totalAddition: 0,
      totalChanges: 0,
      totalTermination: 0,
    },
    {
      health_plan_id: 342,
      health_plan_name: "Cigna",
      health_plan_code: "202",
      health_plan_status: "Cycle Not Configured",
      health_plan_status_date: "",
      health_plan_cycle_name: "",
      health_plan_cycle_start_date: "",
      time_elapsed: null,
      cycle_errors_and_fixes_summary: "",
      is_cycle_reschedule_allowed: false,
      round_id: 0,
      health_plan_round_name: "",
      health_plan_icon_color: "Red",
      health_plan_image_url: "",
      upload_id: 0,
      cycle_id: 0,
      total_provider: 0,
      file_type: 0,
      total_discrepancies: 0,
      fixed: 0,
      excel_url: null,
      totalAddition: 0,
      totalChanges: 0,
      totalTermination: 0,
    },
    {
      health_plan_id: 343,
      health_plan_name: "Amerihealth",
      health_plan_code: "155",
      health_plan_status: "Cycle Not Configured",
      health_plan_status_date: "",
      health_plan_cycle_name: "",
      health_plan_cycle_start_date: "",
      time_elapsed: null,
      cycle_errors_and_fixes_summary: "",
      is_cycle_reschedule_allowed: false,
      round_id: 0,
      health_plan_round_name: "",
      health_plan_icon_color: "Red",
      health_plan_image_url: "",
      upload_id: 0,
      cycle_id: 0,
      total_provider: 0,
      file_type: 0,
      total_discrepancies: 0,
      fixed: 0,
      excel_url: null,
      totalAddition: 0,
      totalChanges: 0,
      totalTermination: 0,
    },
    {
      health_plan_id: 344,
      health_plan_name: "HealthFirst",
      health_plan_code: "303",
      health_plan_status: "File Generation triggered",
      health_plan_status_date: "01/16/2026 09:00 AM",
      health_plan_cycle_name: "16_January_26_21_00",
      health_plan_cycle_start_date: "01/16/2026",
      time_elapsed: "2h 15m",
      cycle_errors_and_fixes_summary: "",
      is_cycle_reschedule_allowed: false,
      round_id: 0,
      health_plan_round_name: "",
      health_plan_icon_color: "Green",
      health_plan_image_url: "",
      upload_id: 0,
      cycle_id: 76339,
      total_provider: 2813,
      file_type: 0,
      total_discrepancies: 0,
      fixed: 0,
      excel_url: "/return_files/full_roster_76339_20260116210000.xlsx",
      totalAddition: 125,
      totalChanges: 45,
      totalTermination: 12,
    },
    {
      health_plan_id: 345,
      health_plan_name: "Tesling",
      health_plan_code: "404",
      health_plan_status: "File Generation triggered",
      health_plan_status_date: "01/17/2026 01:55 AM",
      health_plan_cycle_name: "17_January_26_01_55",
      health_plan_cycle_start_date: "01/17/2026",
      time_elapsed: "1h 30m",
      cycle_errors_and_fixes_summary: "",
      is_cycle_reschedule_allowed: false,
      round_id: 0,
      health_plan_round_name: "",
      health_plan_icon_color: "Green",
      health_plan_image_url: "",
      upload_id: 0,
      cycle_id: 76398,
      total_provider: 0,
      file_type: 0,
      total_discrepancies: 0,
      fixed: 0,
      excel_url: "/return_files/full_roster_76398_20260117015500.xlsx",
      totalAddition: 50,
      totalChanges: 20,
      totalTermination: 5,
    },
  ],
  user_message: "",
}

export const mockCycleHistoryData: Record<number, CycleHistoryResponse> = {
  339: {
    account_id: 0,
    health_plan_id: 339,
    cycle_id: 0,
    cycle_round_id: 0,
    is_successful: true,
    errors: [],
    response_data: [
      {
        id: 24962,
        total_additon: 0,
        total_updates: 0,
        total_terminations: 0,
        cycle_start_date: "01/15/2026",
        cycle_completion_date: "01/15/2026",
        updatedOn: "01/15/2026",
        time_elpased: "0",
        details: "",
        addition_link: "",
        update_link: "",
        termination_link: "",
        excel_url: "/return_files/full_roster_75948_20260115150106.xlsx",
        cycle_name: "15_January_26_15_00",
      },
      {
        id: 24961,
        total_additon: 0,
        total_updates: 0,
        total_terminations: 0,
        cycle_start_date: "01/15/2026",
        cycle_completion_date: "01/15/2026",
        updatedOn: "01/15/2026",
        time_elpased: "0",
        details: "",
        addition_link: "",
        update_link: "",
        termination_link: "",
        excel_url: "/return_files/full_roster_75947_20260115030341.xlsx",
        cycle_name: "15_January_26_03_00",
      },
      {
        id: 24803,
        total_additon: 0,
        total_updates: 0,
        total_terminations: 0,
        cycle_start_date: "01/14/2026",
        cycle_completion_date: "01/14/2026",
        updatedOn: "01/14/2026",
        time_elpased: "0",
        details: "",
        addition_link: "",
        update_link: "",
        termination_link: "",
        excel_url: "/return_files/full_roster_75543_20260114103119.xlsx",
        cycle_name: "14_January_26_21_00",
      },
      {
        id: 24802,
        total_additon: 0,
        total_updates: 0,
        total_terminations: 0,
        cycle_start_date: "01/14/2026",
        cycle_completion_date: "01/14/2026",
        updatedOn: "01/14/2026",
        time_elpased: "0",
        details: "",
        addition_link: "",
        update_link: "",
        termination_link: "",
        excel_url: "/return_files/full_roster_75542_20260114142549.xlsx",
        cycle_name: "14_January_26_14_25",
      },
      {
        id: 24801,
        total_additon: 0,
        total_updates: 0,
        total_terminations: 0,
        cycle_start_date: "01/14/2026",
        cycle_completion_date: "01/14/2026",
        updatedOn: "01/14/2026",
        time_elpased: "0",
        details: "",
        addition_link: "",
        update_link: "",
        termination_link: "",
        excel_url: "/return_files/full_roster_75541_20260114130042.xlsx",
        cycle_name: "14_January_26_13_00",
      },
      {
        id: 24803,
        total_additon: 0,
        total_updates: 0,
        total_terminations: 0,
        cycle_start_date: "01/14/2026",
        cycle_completion_date: "01/14/2026",
        updatedOn: "01/14/2026",
        time_elpased: "0",
        details: "",
        addition_link: "",
        update_link: "",
        termination_link: "",
        excel_url: "/return_files/full_roster_75543_20260114103119.xlsx",
        cycle_name: "14_January_26_09_40",
      },
      {
        id: 24788,
        total_additon: 2813,
        total_updates: 0,
        total_terminations: 0,
        cycle_start_date: "01/14/2026",
        cycle_completion_date: "01/14/2026",
        updatedOn: "01/14/2026",
        time_elpased: "0",
        details: "",
        addition_link: "",
        update_link: "",
        termination_link: "",
        excel_url: "/return_files/full_roster_75522_20260114081658.xlsx",
        cycle_name: "14_January_26_13_46",
      },
    ],
    user_message: "",
  },
  340: {
    account_id: 0,
    health_plan_id: 340,
    cycle_id: 0,
    cycle_round_id: 0,
    is_successful: true,
    errors: [],
    response_data: [
      {
        id: 24965,
        total_additon: 50,
        total_updates: 25,
        total_terminations: 10,
        cycle_start_date: "01/16/2026",
        cycle_completion_date: "01/16/2026",
        updatedOn: "01/16/2026",
        time_elpased: "1h 30m",
        details: "",
        addition_link: "",
        update_link: "",
        termination_link: "",
        excel_url: "/return_files/full_roster_76397_20260116210000.xlsx",
        cycle_name: "16_January_26_21_00",
      },
      {
        id: 24950,
        total_additon: 30,
        total_updates: 15,
        total_terminations: 5,
        cycle_start_date: "01/15/2026",
        cycle_completion_date: "01/15/2026",
        updatedOn: "01/15/2026",
        time_elpased: "2h 10m",
        details: "",
        addition_link: "",
        update_link: "",
        termination_link: "",
        excel_url: "/return_files/full_roster_76396_20260115150000.xlsx",
        cycle_name: "15_January_26_15_00",
      },
    ],
    user_message: "",
  },
}
